apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: garbage-collector-role
  labels:
    app: {{ .Chart.Name }}
rules:
  - apiGroups: ["theia.cloud"]
    resources: ["workspaces"]
    verbs: ["get", "list", "watch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: garbage-collector-rolebinding
  labels:
    app: {{ .Chart.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: garbage-collector-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
