replicaCount: 1
image:
  repository: ghcr.io/ghcr.io/ls1intum/theia/garbage-collector
  tag: latest
  pullPolicy: Always

serviceAccount:
  name: garbage-collector-sa

env:
  WORKSPACE_TTL: "1209600s"
  CHECK_INTERVAL: "1800s"
