on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    uses: ls1intum/.github/.github/workflows/build-and-push-docker-image.yml@feat/docker-run-network
    with:
      docker-file: Dockerfile
      image-name: ghcr.io/ls1intum/theia/garbage-collector
      docker-context: .
      tags: "2024-12-02"
      network: "host"
    secrets: inherit
